### ISSUE TITLE
https feed

### ISSUE THREAD

**Issue by m4lvin** [roundcube/roundcube.github.com#10]
The atom news feed is available at https://roundcube.net/feeds/atom.xml, but it contains a lot of http:// links which lead to mixed-content warnings in feed readers. Ideally, the feed should only contain https:// references iff it is accessed via https.

**Comment by thomascube** [comment]
Fixed.

**Comment by m4lvin** [comment]
Thanks! I think it would be even nicer if also the links after "Download it from" would be https.
