### ISSUE TITLE
Adding contact names to dictionary

### ISSUE THREAD

**Issue by Abatjour3407** [roundcube/roundcube.github.com#25]
Hi

I am really starting to like this platform a lot! In many ways I believe it is even better than Gmail... Thank you so much for this amazing contribution to the web!

A small bug though (and a feature suggestion at the end), **I can't seem to add words to my dictionary**:

I am using Roundcube 1.4 RC1 with the elastic theme. I am using the 'enchant' spell checker and have disabled the spell-checker in my browser. I cannot see the add to dictionary option (see screenshot). I have checked the config file and only see a place to change the dictionary used there.

**Also a related feature idea that would fit in well with this amazing platform could be automatically adding contact names from the address books to the dictionary (like what mobile phones do).**

Thanks again for this excitingly good platform!

![bug10002](https://user-images.githubusercontent.com/50051640/61036320-31287600-a3c9-11e9-97e1-840e631d8f68.png)

**Comment by Abatjour3407** [comment]
I see this has already been addressed in the old roundcube repository: 

> "Search for spellcheck_dictionary in config/defaults.inc.php and move the option to config/config.inc.php with changing the value."

Thanks for that answer, working perfectly now!

I think it is still a valid feature request although I don't know if this is the correct place for feature requests?

**Comment by alecpl** [comment]
That might be a valid feature request, but you should post it at https://github.com/roundcube/roundcubemail/issues
