### ISSUE TITLE
question: is github pages set to enforce https?

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcube.github.com#32]
@thomascube is "Enforce HTTPS" enabled in the GitHub page settings for this repo? (see point 3 https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https)

If so I think we can remove this from `_includes/head.html`
```html
<script>
    var host = '{{ site.enforce_ssl }}';
    if ((host == window.location.host) && (window.location.protocol != 'https:')) {
        window.location.protocol = 'https';
    }
</script>
```

**Comment by thomascube** [comment]
No, it currently isn't. The website is served HTTPS by cloudflare because at the time of setting it all up, Github pages didn't offer https with custom domains.

**Comment by johndoh** [comment]
can I remove that code?

**Comment by thomascube** [comment]
@johndoh No, there's no replacement for it.

**Comment by thomascube** [comment]
I'll try to enable this on Cloudflare but for the time being, we need that fallback.

**Comment by johndoh** [comment]
no problem
