### ISSUE TITLE
Blockquote in dark mode has low contrast

### ISSUE THREAD

**Issue by hebbet** [roundcube/roundcube.github.com#45]
i noticed that `blockquote` on blog has low contrast in dark mode:

https://roundcube.net/news/2021/09/14/spell-roundcube-net-service-down
![image](https://user-images.githubusercontent.com/1423115/135971719-6163fac2-57a5-40f0-a1e2-a8bd372b0cc3.png)

![image](https://user-images.githubusercontent.com/1423115/135971831-be4fdb04-4306-481d-93ed-f2dc7720b722.png)

**Comment by melroy89** [comment]
This issue is RESOLVED and can be closed.
