### ISSUE TITLE
Download Links Broken

### ISSUE THREAD

**Issue by a-bern** [roundcube/roundcube.github.com#64]
hi,

commit 452d5a37a09a0666f7b3127b321485e72256e3bd broke the download links:
`                "url": "https://github.com/roundcube/roundcubemail/releases/download/1.6.8/roundcubemail-1.6.8.tar.gz",` has been changed to
`                "url": "https://github.com/roundcube/roundcubemail/releases/download/1.6.8/roundcubemail-1.6.9.tar.gz",` but should be changed to
`                "url": "https://github.com/roundcube/roundcubemail/releases/download/**1.6.9**/roundcubemail-1.6.9.tar.gz",`

Same for the 1.5 releases

**Comment by alecpl** [comment]
Fixed.
