### ISSUE TITLE
Link to development mailing list from contribute page appears to be incorrect.

### ISSUE THREAD

**Issue by Remmy** [roundcube/roundcube.github.com#65]
On https://roundcube.net/contribute/ , the link to the development mailing list leads to a page (https://lists.roundcube.net/dev) that reads: "Page not found
This page either doesn't exist, or it moved somewhere else." 

I believe it should point to https://lists.roundcube.net/postorius/lists/dev.lists.roundcube.net/ instead.

**Comment by pabzm** [comment]
Thank you very much for your attention and that you took the time to notify us! 🫶 

It just got fixed from @johndoh's perfect contribution.
