### ISSUE TITLE
Provide images with higher resolution for systems with HiDPI/4K displays

### ISSUE THREAD

**Issue by paulmenzel** [roundcube/roundcube.github.com#9]
Accessing the [Roundcube Web site](https://roundcube.net/) with the HiDPI/4K monitor Dell U2718Q several images are blurry.

1.  The logo with text in the top left corner.
2.  The screenshot behind the banner. Though that is probably expected.
3.  The logos of SourceForge.net, Open Hub, and Flint.

**Comment by thomascube** [comment]
Obsolete with the new design using vectorized icons.
